### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by j-rivero** [gazebo-tooling/setup-gazebo#27]
To implement the Windows support we are going to use the great conda-forge packages for Gazebo. See https://anaconda.org/search?q=platform%3Alinux-64+gz-.

Some notes about the gz package on Conda:
 - There are no gz-$collection packages in Conda, so we would need to translate $collection from github actions to return a list of packages (mainly gz-simX). For example: if someone is using gz-harmonic on Windows that should be translated to the package gz-sim9. We might want to add new packages to this translation but for now let's use this $collection -> gz-simX. Remember that https://github.com/gazebo-tooling/gazebodistro host the relationship between collection and packages.
 - If I'm not wrong there are packages only for Garden and Harmonic on conda-forge. Other distributions should return a meaningful error the user.
 - We can probably use the miniconda (package manager) github action https://github.com/marketplace/actions/setup-miniconda

**Comment by traversaro** [comment]
> There are no gz-$collection packages in Conda, so we would need to translate $collection from github actions to return a list of packages (mainly gz-simX). For example: if someone is using gz-harmonic on Windows that should be translated to the package gz-sim9. We might want to add new packages to this translation but for now let's use this $collection -> gz-simX. Remember that https://github.com/gazebo-tooling/gazebodistro host the relationship between collection and packages.

Just as xref (not blocking the work on this great repo), eventually we can add those collection packages, I opened an issue on this in https://github.com/conda-forge/gz-sim-feedstock/issues/61 .
