### ISSUE TITLE
Test job for noble does not run due to the nature of the matrix

### ISSUE THREAD

**Issue by sauk2** [gazebo-tooling/setup-gazebo#39]
## Summary

A test workflow is shown in `test.yml` that installs all the compatible Gazebo+Ubuntu combinations. One job that installs [Harmonic on Noble](https://github.com/gazebo-tooling/setup-gazebo/blob/7748abadd60bc4bd3b3f66c2b2e74979bc8f563e/.github/workflows/test.yml#L64-L65) does not show up due to the nature of the matrix. 

## Implementation suggestions
_Option 1:_ Add a separate job to install the latest compatible Gazebo+Ubuntu combination, which in this case would be Harmonic+Noble. Update for each future release.

_Option 2:_ Add a list of Ubuntu distributions to the matrix and use [`exclude`](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#excluding-matrix-configurations) instead of `include` to prevent the running of incompatible jobs.

**Comment by j-rivero** [comment]
> A test workflow is shown in `test.yml` that installs all the compatible Gazebo+Ubuntu combinations. One job that installs [Harmonic on Noble](https://github.com/gazebo-tooling/setup-gazebo/blob/7748abadd60bc4bd3b3f66c2b2e74979bc8f563e/.github/workflows/test.yml#L64-L65) does not show up due to the nature of the matrix.

Oh I see. The more logical approach to me sound like defining a two-dimension matrix with Ubuntu distributions vs Gazebo collections and include/exclude the necessary combinations. Whatever is easier.

**Comment by sauk2** [comment]
> Oh I see. The more logical approach to me sound like defining a two-dimension matrix with Ubuntu distributions vs Gazebo collections and include/exclude the necessary combinations. Whatever is easier.

We could go for the two-dimensional matrix approach as it does not seem too much work. I will raise a PR for that.

**Comment by j-rivero** [comment]
I think this is solved now, isn't it?

**Comment by sauk2** [comment]
> I think this is solved now, isn't it?

I forgot to make these changes in the previous PRs, so created a new one with the changes.
