### ISSUE TITLE
Parse collections from YAML to get Ubuntu compatibility

### ISSUE THREAD

**Issue by sauk2** [gazebo-tooling/setup-gazebo#49]
## Summary

The current implementation uses an internal object to hold the compatible Gazebo/Ubuntu combinations. Instead of this, it would be effective to parse the collections YAML to get the corresponding Ubuntu distributions.

## Implementation suggestion
This collection file can be parsed to find check the compatible ubuntu distribution 
https://raw.githubusercontent.com/gazebo-tooling/release-tools/master/jenkins-scripts/dsl/gz-collections.yaml

**Comment by j-rivero** [comment]
I'm reopening the issue since we still have the hardcoded the list of Gazebo collections/releases after merging #59. Would be great if we can remove it too and grab it from the yaml file.
